In [1]:
# Numpy Exercises

In [26]:
import numpy as np
import math as math

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [5]:
# How many negative numbers are there?
negative_numbers = a[a < 0]
len(negative_numbers)

4

In [6]:
# How many positive numbers are there?
positive_numbers = a[a > 0]
len(positive_numbers)

5

In [14]:
# How many even positive numbers are there?
even_positive_numbers = positive_numbers[positive_numbers % 2 == 0]
len(even_positive_numbers)

3

In [22]:
# If you were to add 3 to each data point, how many positive numbers would there be?
a_plus_3 = a + 3
positive_a_plus_3 = a_plus_3[a_plus_3 > 0]
len(positive_a_plus_3)

10

In [32]:
# If you squared each number, what would the new mean and standard deviation be?
a_squared = a ** 2
mean_a_squared = np.mean(a_squared)
print('Average = ' + str(mean_a_squared))
std_a_squared = np.std(a_squared)
print('Standard deviation = ' + str(std_a_squared))

Average = 74.0
Standard deviation = 144.0243035046516


In [34]:
# A common statistical operation on a dataset is centering. This means to adjust the data such 
# that the center of the data is at 0. This is done by subtracting the mean from each data point. 
# Center the data set.

In [43]:
mean_a = np.mean(a)
print('a = ' + str(a))
print(str(mean_a) + ' is the mean of a.')
centered_a = [a - mean_a]
centered_a

a = [ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
3.0 is the mean of a.


[array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
        -10.])]

In [45]:
# Calculate the z-score for each data point. Recall that the z-score is given by:
# Z = (x - mean) / std
std_a = np.std(a)
z_score = [(a - mean_a) / std_a]
z_score

[array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
        -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
         0.        , -1.24034735])]

In [149]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print('a = ' + str(a))

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
print('Sum of a = ' + str(sum_of_a))

# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)
print('Min of a = ' + str(min_of_a))

# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(a)
print('Max of a = ' + str(max_of_a))

# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
sum_of_a = 0
for n in a:
    sum_of_a += n
mean_of_a = sum_of_a / len(a)
print('Mean of a = ' + str(mean_of_a))

# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = 1
for n in a:
    product_of_a *= n

print('The product of all elements in a = ' + str(product_of_a))

# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = []
for n in a:
    square_root = n ** (1/2)
    squares_of_a.append(square_root)
print('The square roots of the elements in a = ' + str(squares_of_a))

# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = []
for n in a:
    if n % 2 != 0:
        odds_in_a.append(n)
print('The odd numbers in a = ' + str(odds_in_a))

# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = []
for n in a:
    if n % 2 == 0:
        evens_in_a.append(n)
print('The even numbers in d = ' + str(evens_in_a))

a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Sum of a = 55
Min of a = 1
Max of a = 10
Mean of a = 5.5
The product of all elements in a = 3628800
The square roots of the elements in a = [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0, 3.1622776601683795]
The odd numbers in a = [1, 3, 5, 7, 9]
The even numbers in d = [2, 4, 6, 8, 10]


In [100]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])
print('b = \n' +str(b))
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = np.sum(b)
print('Sum of b = ' + str(sum_of_b))

# Exercise 2 - refactor the following to use numpy.  
min_of_b = np.min(b)
print('The min of b = ' + str(min_of_b))

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = np.max(b)
print('The max of b = ' + str(max_of_b))


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = np.mean(b)
print('The mean of b = ' + str(mean_of_b))


# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = np.prod(b)
print('The product of all elements of b = ' + str(product_of_b))

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = np.square(b)
print('The elements of b squared = \n' + str(squares_of_b))

# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = b[b % 2 != 0]
print('The odds in b = ' + str(odds_in_b))

# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = b[b % 2 == 0]
print('The evens in b = ' + str(evens_in_b))

# Exercise 9 - print out the shape of the array b.

print('The shape of b = ' + str(np.shape(b)))

# Exercise 10 - transpose the array b.

b_transpose = np.transpose(b)
print('B transposed = ' + '\n' + str(b_transpose))

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b_1x6 = np.reshape(b, (1, 6))
print('B reshaped to a 1 x 6 = ' +str(b_1x6))

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

b_6x1 = np.reshape(b, (6, 1))
print('B reshaped to 6 a 6 x 1 = \n' + str(b_6x1))


b = 
[[3 4 5]
 [6 7 8]]
Sum of b = 33
The min of b = 3
The max of b = 8
The mean of b = 5.5
The product of all elements of b = 20160
The elements of b squared = 
[[ 9 16 25]
 [36 49 64]]
The odds in b = [3 5 7]
The evens in b = [4 6 8]
The shape of b = (2, 3)
B transposed = 
[[3 6]
 [4 7]
 [5 8]]
B reshaped to a 1 x 6 = [[3 4 5 6 7 8]]
B reshaped to 6 a 6 x 1 = 
[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [115]:
## Setup 3
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print('c = \n' + str(c))
# 
# Exercise 1 - Find the min, max, sum, and product of c.

min_c = np.min(c)
print('The min of c = ' + str(min_c))

max_c = np.max(c)
print('The max of c = ' + str(max_c))

prod_c = np.prod(c)
print('The product of c = ' + str(prod_c))

# Exercise 2 - Determine the standard deviation of c.

std_c = np.std(c)
print('The std of c = ' + str(std_c))

# Exercise 3 - Determine the variance of c.

var_c = np.var(c)
print('The variance of c = ' + str(var_c))

# Exercise 4 - Print out the shape of the array c

shape_c = np.shape(c)
print('The shape of c = ' + str(shape_c))

# Exercise 5 - Transpose c and print out transposed result.

transpose_c = np.transpose(c)
print('The transpose of c = \n' + str(transpose_c))

# Exercise 6 - Multiply c by the c-Transposed and print the result.

prod_c_x_ctrasnposed = c * transpose_c
print('The product of c * c_transposed = \n' + str(prod_c_x_ctrasnposed))

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

sum_prod_c_x_ctransposed = np.sum(prod_c_x_ctrasnposed)
print('The sum of the product of c * c_transposed = ' + str(sum_prod_c_x_ctransposed))

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
 
prod_prod_c_x_ctransposed = np.prod(prod_c_x_ctrasnposed)
print('The product of c * c_transposed = ' + str(prod_prod_c_x_ctransposed))


c = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The min of c = 1
The max of c = 9
The product of c = 362880
The std of c = 2.581988897471611
The variance of c = 6.666666666666667
The shape of c = (3, 3)
The transpose of c = 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
The product of c * c_transposed = 
[[ 1  8 21]
 [ 8 25 48]
 [21 48 81]]
The sum of the product of c * c_transposed = 261
The product of c * c_transposed = 131681894400


In [130]:
## Setup 4
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])
print('d = \n' + str(d))

# Exercise 1 - Find the sine of all the numbers in d

sine_d = np.sin(d)
print('The sin of d = \n' + str(sine_d))

# Exercise 2 - Find the cosine of all the numbers in d

cosine_d = np.cos(d)
print('The cosine of d = \n' + str(cosine_d))

# Exercise 3 - Find the tangent of all the numbers in d

tangent_d = np.tan(d)
print('The tan of d = \n' + str(tangent_d))

# Exercise 4 - Find all the negative numbers in d

negative_d = d[d < 0]
print('The negative numbers in d = ' + str(negative_d))

# Exercise 5 - Find all the positive numbers in d

positive_d = d[d > 0]
print('The positive numbers in d = ' + str(positive_d))

# Exercise 6 - Return an array of only the unique numbers in d.

unique_d = np.unique(d)
print('The unique numbers in d = ' + str(unique_d))

# Exercise 7 - Determine how many unique numbers there are in d.

len_unique_d = len(unique_d)
print('The number of unique numbers in d = ' + str(len_unique_d))

# Exercise 8 - Print out the shape of d.

shape_d = np.shape(d)
print('The shape of d = ' + str(shape_d))

# Exercise 9 - Transpose and then print out the shape of d.

transpose_d = np.transpose(d)
print('The transpose of d = \n' + str(transpose_d))
shape_transpose_d = np.shape(transpose_d)
print('The shape of the transpose of d = ' + str(shape_transpose_d))

# Exercise 10 - Reshape d into an array of 9 x 2

rs_d_9x2 = np.reshape(d, (9,2))
print('d reshaped into a 9 x 2 = \n' + str(rs_d_9x2))

d = 
[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]
The sin of d = 
[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]
The cosine of d = 
[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]
The tan of d = 
[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]
The negative numbers in d = [-90 -30 -45 -45]
The positive numbers in d = [ 90  30  45 120 180  45 270  90  60  45  90 180]
The unique numbers in d = [-90 -45 -30   0  30  45  60  90 1